Addserverespec
Junsei-Ogr/raisetech-circleci-automation pull request #6
Opened 2022-08-29 15:15 UTC by Junsei-Ogr

@yuta-ushijima

ウシジマさん、お疲れ様です！またまた前回から時間が経ってしまったのですが、
最後の課題の「Circle CIでServerspecを動かす」に着手しました。
Serverspecの導入の前にrubyのインストールが必要だと思うのですが、
ansibleをインストールさせた際と同じように、config.ymlにrubyをインストールする記述を追加したら良いのでしょうか。

2022-08-30 00:11 UTC, yuta-ushijima commented
>ansibleをインストールさせた際と同じように、config.ymlにrubyをインストールする記述を追加したら良いのでしょうか。

そうですね！
おっしゃる通りcircleciの設定ファイルにrubyをinstallして、serverspecを実行できるようにする必要があります！
あとはserverspecはsshで対象のサーバーに対してテストを実行できるようにしなければならないので、そこも設定が必要です！

2022-12-06 14:59 UTC, Junsei-Ogr commented
お疲れ様です。2021年8月度の受講生だった小椋と申します。

以前のカリキュラムの課題についてになるのですが、質問させてください。
ご確認よろしくお願いいたします。



```
課題タイトル、詳細
15回課題　Ansibleを使った環境設定のコード化。
Ansibleを使った環境設定のコード化をやってみましょう。
過去の課題を進めた時のコマンドの記録はとってありますか？それがあれば変換していくだけです。それでも仕組みが見えてくるまでは難しいと思います。○記録をとっていなかった人は、どんなことをやったか思い出しながら進めましょう。○終わったらServerSpecのテスト含め、CircleCIで実行できるように連携させてみましょう。

```

最後の課題の「Circle CIでServerspecを動かす」に取り掛かるため、config.ymlにrubyをインストールする記述を追加するべく、[https://circleci.com/developer/ja/orbs/orb/circleci/ruby](url)や[https://qiita.com/RiSE_blackbird/items/c0f23ca2c78499fad1b5](url)を参考に追加してみたのですが、CircliCIにて確認すると[https://app.circleci.com/pipelines/github/Junsei-Ogr/raisetech-circleci-automation](url)configにエラーがあるとでました。

記述の形式が異なっているためでしょうか。また、記述を追加する箇所が間違っているのでしょうか。
前回取り組んでから時間が経ってしまっているため、全く見当違いな質問になっていたら申し訳無いのですが、
ご確認頂けると幸いです。

2023-06-09 14:22 UTC, Junsei-Ogr commented
> お疲れ様です。2021年8月度の受講生だった小椋と申します。
> 
> 以前のカリキュラムの課題についてになるのですが、質問させてください。 ご確認よろしくお願いいたします。
> 
> ```
> 課題タイトル、詳細
> 15回課題　Ansibleを使った環境設定のコード化。
> Ansibleを使った環境設定のコード化をやってみましょう。
> 過去の課題を進めた時のコマンドの記録はとってありますか？
> それがあれば変換していくだけです。それでも仕組みが見えてくるまでは難しいと思います。
> ○記録をとっていなかった人は、どんなことをやったか思い出しながら進めましょう。
> ○終わったらServerSpecのテスト含め、CircleCIで実行できるように連携させてみましょう。
> ```
> 

前回質問させて頂いてからまたまた時間が経ってしまっていますが、
旧カリキュラム15回課題のご確認をお願いしたいです。

RubyとServerspecインストール、テストを実行しています。

2023-06-10 03:43 UTC, MasatoshiMizumoto requested changes
コメント入れましたのでご対応ください！

2023-06-10 03:43 UTC, MasatoshiMizumoto commented on hosts/inventory
空行なし警告が出てますね！

2023-06-10 03:43 UTC, MasatoshiMizumoto commented on playbook.yml
空行なし警告が出てますね！

2023-06-10 03:43 UTC, MasatoshiMizumoto commented on spec/test_spec.rb
空行なし警告が出てますね！

2023-06-10 03:43 UTC, MasatoshiMizumoto commented on .circleci/config.yml
> +            if aws cloudformation describe-stacks --stack-name $STACK_NAME --region $REGION >/dev/null 2>&1; then
`cloudformation deploy`でここ置換できないでしょうかね？？

2023-06-12 15:51 UTC, Junsei-Ogr commented
@MasatoshiMizumoto 

![image](https://github.com/Junsei-Ogr/raisetech-circleci-automation/assets/89210714/bf364918-7149-4fd7-989b-a58baaec8fc8)

ご確認ありがとうございます。
ご指摘頂いた通り、`wait`なしで再度挑戦してみたところCIが通りました！

2023-06-12 15:55 UTC, MasatoshiMizumoto requested changes
空行の警告がまだ出てますのでご確認いただきたいです！
VSCodeの設定で防げるのでやったほうが良いかもです。

2023-06-12 15:55 UTC, MasatoshiMizumoto commented on playbook.yml
空行の警告が出てますね！

2023-06-12 15:55 UTC, MasatoshiMizumoto commented on sample_stack.yml
空行の警告が出てますね！

2023-06-12 23:54 UTC, Junsei-Ogr commented on sample_stack.yml
> 空行の警告が出てますね！

@MasatoshiMizumoto 
ご確認ありがとうございます。
お疲れ様です！空行対応いたしました！
再度ご確認よろしくお願いいたします。

2023-06-13 01:52 UTC, MasatoshiMizumoto approved these changes
ちゃんとCIも成功してますしいいですね！
LGTM!

2023-06-13 13:33 UTC, merged